export enum ActionType {
  FETCH_BOOKS = 'FETCH_BOOKS',
  WRITE_DATA = 'WRITE_DATA',
  FETCH_ABOUT = 'FETCH_ABOUT',
  FETCH_FAQS = 'FETCH_FAQS',
  FETCH_LINKS = 'FETCH_LINKS',
  BORROW_BOOK = 'BORROW_BOOK',
  VERIFY_USER = 'VERIFY_USER',
  LOG_USER = 'LOG_USER',
}
export enum MutationType {
  UPDATE_BOOKS = 'UPDATE_BOOKS',
  UPDATE_ABOUT = 'UPDATE_ABOUT',
  UPDATE_FAQS = 'UPDATE_FAQS',
  UPDATE_LINKS = 'UPDATE_LINKS',
}
export enum GetterType {
  BOOKS = 'GET_BOOKS',
  BOOK = 'GET_BOOK',
  ABOUT_SECTIONS = 'GET_ABOUT_SECTIONS',
  ACTIVE_MEMBERS = 'GET_ACTIVE_MEMBERS',
  OLD_MEMBERS = 'GET_OLD_MEMBERS',
  FAQS = 'FAQS',
  TELE_LINK = 'TELE_LINK',
  INSTA_LINK = 'INSTA_LINK',
  REGISTER_LINK = 'REGISTER_LINK',
}
